# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Isaac Van Name
email: info@isaacvanname.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer with over 10 years of web development experience
  and I've led or contributed to over 50 projects. In my spare time, I am a 
  competitive chessplayer, retro video game collector, and avid craft beer fan.
  Above all, though, I am a proud father. 
baseurl: "/jekyll-simple" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: IsaacVanName
github_username:  IsaacVanName

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
